### ISSUE TITLE
Wrangle the data in preparation for machine learning

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/dsci_525_group_22#23]
Our data currently covers all of NSW, but say that our client wants us to create a machine learning model to predict rainfall over Sydney only. There's a bit of wrangling that needs to be done for that:

We need to query our data for only the rows that contain information covering Sydney
We need to wrangle our data into a format suitable for training a machine learning model. That will require pivoting, resampling, grouping, etc.
To train an ML algorithm we need it to look like this:

<html>
<body>

  | model-1_rainfall | model-2_rainfall | model-3_rainfall | ... | observed_rainfall
-- | -- | -- | -- | -- | --
0 | 0.12 | 0.43 | 0.35 | ... | 0.31
1 | 1.22 | 0.91 | 1.68 | ... | 1.34
2 | 0.68 | 0.29 | 0.41 | ... | 0.57

</body>
</html>

Get the data from s3 (combined_model_data_parti.parquet and observed_daily_rainfall_SYD.csv)

6.2) First query for Sydney data and then drop the lat and lon columns (we don't need them).

syd_lat = -33.86
syd_lon = 151.21
Expected shape (1150049, 2).

6.3) Save this processed file to s3 for later use:

Save as a csv file ml_data_SYD.csv to s3://mds-s3-xxx/output/ expected shape (46020,26) - This includes all the models as columns and also adding additional column Observed loaded from observed_daily_rainfall_SYD.csv from s3.

This should be done in the appropriate section of the milestone 2 ipynb

**Comment by veerupandey** [comment]
Done! https://s3.console.aws.amazon.com/s3/object/mds-s3-22?region=us-west-2&prefix=output/ml_data_SYD.csv
